# Generated by Django 5.0.6 on 2024-05-25 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qualification",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="qualification_specialization",
                to="app.specialization",
            ),
        ),
    ]
