# Generated by Django 5.0.6 on 2024-05-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_group_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_qualification",
                to="app.qualification",
            ),
        ),
    ]
