# Generated by Django 5.0.6 on 2024-05-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_student_qualification"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Группа", "verbose_name_plural": "Группа"},
        ),
        migrations.AlterModelOptions(
            name="qualification",
            options={
                "verbose_name": "Квалификация",
                "verbose_name_plural": "Квалификация",
            },
        ),
        migrations.AlterModelOptions(
            name="specialization",
            options={
                "verbose_name": "Специализация",
                "verbose_name_plural": "Специализация",
            },
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Студент", "verbose_name_plural": "Студент"},
        ),
        migrations.AlterModelTable(
            name="group",
            table="group",
        ),
    ]
