# Generated by Django 5.0.6 on 2024-05-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_studentgroup_options_alter_studentgroup_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Ожидание"),
                    (2, "Поступил"),
                    (3, "Не поступил"),
                    (4, "Забрал документы"),
                ],
                default=1,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="student_group_student",
                to="app.student",
            ),
        ),
    ]
