# Generated by Django 5.0.6 on 2024-05-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_student_status_alter_studentgroup_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualification",
            name="number",
            field=models.CharField(
                default=123, max_length=30, verbose_name="Шифр квалификации"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="specialization",
            name="number",
            field=models.CharField(
                default=123, max_length=30, verbose_name="Шифр специальности"
            ),
            preserve_default=False,
        ),
    ]
